### ISSUE TITLE
Tutorial agar running di windows

### ISSUE THREAD

**Issue by ilhamiarie** [gojigeje/wasapbot#1]
Halo @gojigeje. apakah ada tutorial agar bisa berjalan di windows..? terima kasih sebelumnya

**Comment by gojigeje** [comment]
Saya kurang tahu dan belum pernah mencoba di windows. sebaiknya cek di repository [WHAnonymous/Chat-API, terutama di bagian issue](https://github.com/WHAnonymous/Chat-API/search?p=1&q=windows&type=Issues&utf8=%E2%9C%93) karena wasapbot menggunakan library tersebut.

Namun dari yang saya baca untuk menjalankan chat-api di windows saat ini masih belum semudah di linux, terutama karena membutuhkan kompilasi dan instalasi module PHP tambahan (di linux tinggal ketik beberapa command).

Saya sarankan untuk menjalankan di linux, jika di pc tidak ada linux, bisa mencoba di vps, dan kalau perlu vps, saya bisa sediakan yang harganya agak miring harganya (ujung-ujungnya promosi :grin:).

Saya close issue-nya karena lebih relevan ke repo Chat-API.
Anyway.. semoga sukses projectnya!
