### ISSUE TITLE
Auto Reconnect Ketika Koneksi putus

### ISSUE THREAD

**Issue by ilhamiarie** [gojigeje/wasapbot#2]
Halo @gojigeje, trima kasih atas kodenya.
Saya sudah menggunakan kode yang @gojigeje buat, dan berjalan dengan baik (terima kasih). Cuma kadang dia close sendiri ketika koneksi internet terputus. Apakah bisa dibuat kode khusus, utk mengecek session di WA nya, dengan tujuan ketika, disconect bisa koneksi automatis. Terima kasih

**Comment by gojigeje** [comment]
Halo gan,,
sebenarnya sudah ada fungsi deteksi koneksi yg putus kok di scriptnya. Pertama deteksi putusnya koneksi script dengan server whatsapp dengan _event_ `onClose`, dan kedua deteksi putusnya pc/laptop lokal (tempat menjalankan script) dari koneksi internet, dengan function `cek_konek()`yang dilakukan setiap kelipatan 100 dari variabel `$poll` (baris 100).

Seharusnya ketika mengalami 2 hal tsb script akan otomatis reload/restart alias mengulangi proses login lagi dari awal dst, kalau di tempat agan @ilhamiarie dia langsung putus dan tidak restart, coba diperiksa di bagian log.. semoga membantu
