### ISSUE TITLE
Nomor Ter-banned

### ISSUE THREAD

**Issue by ilhamiarie** [gojigeje/wasapbot#3]
Gan, kenapa ya account wa mudah ter banned..? saya sdh berulang2 kali registrasi pakai register tool.. blm 2 jam ter banned.. saya pakai kode si agan.

**Comment by gojigeje** [comment]
hai gan.. kalau dibaca2 di issue chat-api akhir2 ini memang whatsapp sedang gencar2 ngeblok akun wa yang tidak resmi, coba iseng baca di issue chat-api. terutama akun-akun baru yang baru register.

Saya kemarin coba register juga kena block. tapi saya juga ada bot yang udah jalan selama setengah tahun lebih (sampai sekarang untungnya masih jalan)..

Afaik, chat-api memang belum menggunakan basis kode API WhatsApp yang terbaru (protokol whatsapp terbaru). Kita cuma bisa nunggu aja dan berharap gan.. semoga library chat-api tetap dikembangkan dan syukur2 bisa update ke protokol terbaru :cry:
