### ISSUE TITLE
it still works?

### ISSUE THREAD

**Issue by ciungulete** [gojigeje/wasapbot#5]
I try today but don't work

root@localhost:/home/wasapbot# php wasapbot.php
https://github.com/gojigeje/wasapbot.git[1][16:54:52] ---------------------------------------------------------
[1][16:54:52] - Login as 'wasapbot' (407XXXXXXXX)
[1][16:54:55] - 40748365325 logged in..!
[1][16:54:55] - Wait until the bot is ready..!
[1][16:54:55] ---------------------------------------------------------
PHP Warning:  socket_write(): unable to write to socket [32]: Broken pipe in /home/wasapbot/whatsapp/src/whatsprot.class.php on line 2753
PHP Stack trace:
PHP   1. {main}() /home/wasapbot/wasapbot.php:0
PHP   2. WhatsProt->loginWithPassword() /home/wasapbot/wasapbot.php:70
PHP   3. Login->doLogin() /home/wasapbot/whatsapp/src/whatsprot.class.php:286
PHP   4. WhatsProt->pollMessage() /home/wasapbot/whatsapp/src/Login.php:49
PHP   5. WhatsProt->sendPing() /home/wasapbot/whatsapp/src/whatsprot.class.php:317
PHP   6. WhatsProt->sendNode() /home/wasapbot/whatsapp/src/whatsprot.class.php:1075
PHP   7. WhatsProt->sendData() /home/wasapbot/whatsapp/src/whatsprot.class.php:2932
PHP   8. socket_write() /home/wasapbot/whatsapp/src/whatsprot.class.php:2753

[1][16:56:58] - Something wrong, restarting bot.

I recive this message with chat-api...

Any solutions?

**Comment by gojigeje** [comment]
Sorry, I don't think this is going to work anymore :cry: 

The development of the library I used for this project was stopped by its author (https://github.com/mgp25/Chat-API), so I'm not going to update this project.

Check this alternative library written in python > [yowsup](https://github.com/tgalal/yowsup/).

**Comment by lazyw0lf** [comment]
Having same issue here with sendData() ... did you found a way to let this work or tried yousup? Thanks

**Comment by ghost** [comment]
The Chat-API stopped working which was the main base for this script.
It may/may not work, depending upon the author of Chat-API that he updates it or not.



Regards
**Aryan Chauhan**

**Comment by charanjit-singh** [comment]
Why!
