### ISSUE TITLE
oldversion

### ISSUE THREAD

**Issue by singhalpiyush12** [gojigeje/wasapbot#6]
[status] => fail
    [reason] => old_version
while running registerTool.php

**Comment by singhalpiyush12** [comment]
i got password from yowsup  and changed the credentials mentioned in readme .
Now on running wasapbot.php 
[1][14:37:46] - Something wrong, restarting bot..
error appears

**Comment by gojigeje** [comment]
I'm not maintaining this project anymore. Sorry
